### ISSUE TITLE
Copy Image Not Working

### ISSUE THREAD

**Issue by apoorvemohan** [CCI-MOC/ims#146]
Sourabh and I were testing the copy functionality and we got the following error:

DEBUG - 2017-09-19,18:17:29..452 - File '/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/einstein/operations.py', line 62 in __exit__
Exiting shutdown with return value = None
Traceback (most recent call last):
  File "/usr/bin/bmi", line 9, in <module>
    load_entry_point('ims==0.3', 'console_scripts', 'bmi')()
  File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-6.6-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/cli/cli.py", line 38, in function_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/cli/cli.py", line 517, in copy_image
    ret = bmi.copy_image(img1, dest_project, img2)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 31, in func_wrapper
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/einstein/operations.py", line 510, in copy_image
    ceph_name = self.__get_ceph_image_name(img2, dest_project)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 59, in func_wrapper
    ret = func(*args, **kwargs)
TypeError: __get_ceph_image_name() takes exactly 2 arguments (3 given)

Upon further investigation, we found that the fix to this error was proposed in one of the PR's that got closed. Also, the copy function is not flattening the image.

**Comment by chemistry-sourabh** [comment]
Merged Fix
