### ISSUE TITLE
Image Copy Between projects Fails

### ISSUE THREAD

**Issue by apoorvemohan** [CCI-MOC/ims#157]
Copying image between two projects fails. 

[root@kumo-bmi-no-seccloud apoorve]# bmi cp bmi_infra centos_67_e1_modified jon sesa_centos67
Traceback (most recent call last):
  File "/bin/bmi", line 9, in <module>
    load_entry_point('ims==0.3', 'console_scripts', 'bmi')()
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/cli/cli.py", line 40, in function_wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/cli/cli.py", line 520, in copy_image
    ret = bmi.copy_image(img1, dest_project, img2)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 32, in func_wrapper
    ret = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/einstein/operations.py", line 569, in copy_image
    ceph_name = self.__get_ceph_image_name(img2, dest_project)
  File "/usr/lib/python2.7/site-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 60, in func_wrapper
    ret = func(*args, **kwargs)
TypeError: __get_ceph_image_name() takes exactly 2 arguments (3 given)

"__get_ceph_image_name()" in operations.py accepts 1 argument whereas the "copy_image()" in operation.py passes 2 arguments when calling it (the second argument being the destination project).

**Comment by chemistry-sourabh** [comment]
@apoorvemohan check if this is fixed

**Comment by apoorvemohan** [comment]
Fixed with PR #146
