### ISSUE TITLE
Ceph Error when running bmi as bmi user

### ISSUE THREAD

**Issue by chemistry-sourabh** [CCI-MOC/ims#92]
As all of you know I am trying to containerize bmi for easy deployment of light weight dev and production.

Tried installing bmi with proper permissions ( #89 )  for production deployment. Tried running bmi db ls as bmi user, but landed with this error.

```
Traceback (most recent call last):
  File "/usr/local/bin/bmi", line 9, in <module>
    load_entry_point('ims==0.3', 'console_scripts', 'bmi')()
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click-6.7-py2.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/cli/cli.py", line 40, in function_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/cli/cli.py", line 431, in list_all_images
    with BMI(_username, _password, constants.BMI_ADMIN_PROJECT) as bmi:
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 32, in func_wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/einstein/operations.py", line 57, in __init__
    self.cfg.iscsi.password)
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 32, in func_wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/einstein/ceph.py", line 24, in __init__
    self.cluster = self.__init_cluster()
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/common/log.py", line 60, in func_wrapper
    ret = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ims-0.3-py2.7.egg/ims/einstein/ceph.py", line 52, in __init_cluster
    cluster.connect()
  File "rados.pyx", line 785, in rados.Rados.connect (/build/ceph-RG9HEH/ceph-10.2.6/src/build/rados.c:10073)
rados.ObjectNotFound: error connecting to the cluster
```

I need to do sudo rbd ls to see the images in ceph. Regular rbd ls doesn't work, it gives a unable to connect to cluster. Error is not observed when running as root.

I am guessing it is some permissions issue. @sirushtim and @ravisantoshgudimetla any ideas ?

**Comment by apoorvemohan** [comment]
Was the ceph pool and Id configured correctly?

**Comment by chemistry-sourabh** [comment]
I am able to a sudo rbd ls without giving any --id or --pool, but not able to a rbd ls

**Comment by apoorvemohan** [comment]
Ceph args must be configured in .bashrc of root user and not for "user" user

**Comment by chemistry-sourabh** [comment]
Ceph args are not configured for root but it works in root. I tried giving --id and --pool to "user"s rbd, but got the same error.

**Comment by apoorvemohan** [comment]
Where are you testing this?

**Comment by chemistry-sourabh** [comment]
in a container

**Comment by apoorvemohan** [comment]
On which machine?

**Comment by chemistry-sourabh** [comment]
on my mac

**Comment by apoorvemohan** [comment]
How are you connecting to CEPH?

**Comment by chemistry-sourabh** [comment]
Deployed a ceph container on my mac. Connecting through dockers internal network

**Comment by apoorvemohan** [comment]
I meant which ceph are you connecting to?

**Comment by chemistry-sourabh** [comment]
You mean version ? The latest available. I am connecting to the ceph container on my mac not neu or any other physical deployment.

**Comment by apoorvemohan** [comment]
Cam you paste what error you are getting when running from shell?

**Comment by chemistry-sourabh** [comment]
Its above

**Comment by apoorvemohan** [comment]
Isn't that the error when running from python? Can you run without python from the user user and paste the error

**Comment by chemistry-sourabh** [comment]
The one in the comment is from rbd ls. The one in the issue description is from bmi db ls

**Comment by chemistry-sourabh** [comment]
90% I missed some key setup thing for client. I am sure rado or laura will be to solve this

**Comment by apoorvemohan** [comment]
Why does it shows /user/local/bin/bmi in the second line of the error?

**Comment by chemistry-sourabh** [comment]
Thats where it is installed

**Comment by apoorvemohan** [comment]
Can you somehow give me access to the machine? I want to debug few things.

**Comment by chemistry-sourabh** [comment]
Hmmm its on my mac.

**Comment by chemistry-sourabh** [comment]
or I can raise PR for the docker scripts and you can run on your own system

**Comment by chemistry-sourabh** [comment]
@apoorvemohan #93

**Comment by chemistry-sourabh** [comment]
Ok update, added the client section in ceph.conf with keyring option, this changed the error to permission denied, but Ceph stopped working as both the client and server are using same ceph.conf file.

So Removed the client section and added --keyring to cli, got permission denied. Also we are not passing keyring to the rados python object so couldn't test that.

**Comment by chemistry-sourabh** [comment]
Looks like changing the ownership of keyring file to bmi:bmi fixed it. bmi db ls and rbd ls are working with bmi user.

But on the bmi vm, the keyring file is owned by root and it still works. I guess it is due to 644 permissions, but by default keyring has 600 permission. So was wondering which is the right way to fix it ? Change the ownership or permissions ? I feel it is ownership.

@CCI-MOC/bmi-breakers suggestions ?

**Comment by chemistry-sourabh** [comment]
http://docs.ceph.com/docs/kraken/rados/operations/user-management/

**Comment by ravisantoshgudimetla** [comment]
So, it should be with bmi:bmi. Rule of thumb, never leave any file with root access if it is needed by your software.

**Comment by chemistry-sourabh** [comment]
ok thought so

**Comment by chemistry-sourabh** [comment]
Changing the ownership of keyring to bmi:bmi fixed this issue
